[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/web/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[[services]]
name = "odoo"

[services.variables]
PGHOST = { $ref = "PGHOST" }
PGPORT = { $ref = "PGPORT" }
PGUSER = { $ref = "PGUSER" }
PGPASSWORD = { $ref = "PGPASSWORD" }
PGDATABASE = { $ref = "PGDATABASE" }
ADMIN_PASSWORD = { $ref = "ADMIN_PASSWORD" }
